const LOAD_TRANSLATIONS = 'LOAD_TRANSLATIONS';
const SET_DEFAULT_LANGUAGE = 'SET_DEFAULT_LANGUAGE';
const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const ACTION_TYPES = {
  LOAD_TRANSLATIONS,
  SET_DEFAULT_LANGUAGE,
  CHANGE_LANGUAGE,
  LOGIN_SUCCESS
};
