const LOAD_TRANSLATIONS = 'LOAD_TRANSLATIONS';
const SET_DEFAULT_LANGUAGE = 'SET_DEFAULT_LANGUAGE';
const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
const CURRENT_USER = 'CURRENT_USER';
const LOGOUT = 'LOGOUT';

export const ACTION_TYPES = {
  LOAD_TRANSLATIONS,
  SET_DEFAULT_LANGUAGE,
  CHANGE_LANGUAGE,
  CURRENT_USER,
  LOGOUT
};
